name: build-validate-publish

# This workflow runs on pull requests and pushes to the main branch, and
# builds/validates the specs, other documents, and supplemental materials.
# This includes verifying the WGSL grammar which is one of the generated
# supplemental materials.
#
# On pushes to the main branch, it also publishes the outputs to GitHub Pages.

on:
  pull_request:
    paths-ignore: [ "Dockerfile" ]
  push:
    branches: [main]
    paths-ignore: [ "Dockerfile" ]
  # Allows admins to trigger the workflow manually from GitHub's UI.
  workflow_dispatch:

jobs:
  # Note, spec-prod can publish to gh-pages as well, but we use a custom publish
  # step to publish additional files anyway, so we use that instead of making
  # many separate gh-pages commits (one per bikeshed file + one for extras).
  build-validate-publish:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:main
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.github_token }}

    steps:
      - uses: actions/checkout@v3
      
      - name: Prepare container
        run: |
          sudo -u pptruser -s <<EOF
          cp -r /grammar ./wgsl/
          git init

      - name: Build and validate
        run: |
          sudo -u pptruser -s <<EOF
          export PATH="$(python3 -m site --user-base)/bin:${PATH}"
          BIKESHED_DISALLOW_ONLINE=1 REQUIRE_DIAGRAM_GENERATION=1 make -j out
          # Ensure diagrams didn't change after regeneration
          sh tools/check-repo-clean.sh

      - name: Deploy to GitHub Pages
        if: ${{ success() && github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          BRANCH: gh-pages
          FOLDER: out
